### ISSUE TITLE
Helios2Mqtt Crashes some seconds after  connection

### ISSUE THREAD

**Issue by satisfied83** [mreschka/helios2mqtt#3]
I installed V0.1.8 and just tried to connect to helios kwl500. Connection to mqtt is established and also first values can be seen on mqtt broker side (status topic and connected item).

After few seconds helios2mqtt crashes, refer to added log information

```
2020-11-20 15:01:48.336 <info>  mqtt connected mqtt://127.0.0.1
(node:21026) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at /usr/lib/node_modules/helios2mqtt/helios.js:190:168
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mreschka** [comment]
Sorry for the late reply - This seems to be a problem with an unforseen response in helios2mqtt from your Helios. Could you please add the parameter "-v debug" to your cmdline, so we can see what exactly happes here?
